--------------------------------------------------------------------------------
-- kairos_defence.lua
-- Auto-generated by make_apply_bundles_lua.py.
-- Effect bundles: 17   Default duration: permanent
--
-- Run via the TWW3 "run arbitrary lua" console mod. Applies each effect bundle
-- below to the SELECTED lord's ARMY (or the faction leader's) via
--     cm:apply_effect_bundle_to_force(bundle_key, military_force_cqi, TURNS)
-- Bundles carry FORCE-scope effects, so these buff every unit in the army.
--
-- Combined army-wide effect of this set:
--   * Melee defence: +44
--   * Melee attack: +10
--   * Armour: +7%
--   * Armour: +65
--   * Weapon strength: +10%
--   * Missile resistance: +45%
--   * Attribute: +360 Missile Block
--   * Ability number of uses: +3 for "Celestial Intervention"
--   * Missile block chance: +15%
--   * Speed: +45%
--   * Physical resistance: +40%
--   * Leadership: +6
--   * Ward save: +15%
--   * Barrier hit points: +65%
--   * Ammunition: +50%
--   * Range: +50%
--   * Army ability: "Celestial Intervention"
--   * Instantly heals all units in the army
--------------------------------------------------------------------------------

local APPLY_TO = "character"   -- "character" (selected) or "faction" (leader)
local TURNS    = 0            -- 0 = permanent (until removed); >0 = lasts N turns

-- effect_bundle ids to apply to the army
local BUNDLES = {
    "wh2_main_incident_all_melee_defense_up",  -- Defensive Drills
    "wh3_main_dilemma_ogr_6_first",  -- A Hearty Brunch
    "wh3_dlc25_nur_battle_1_positive_blessed",  -- +8 MD (untitled)
    "wh3_main_incident_nur_8",  -- Chicken-Scratch
    "wh3_dlc25_nur_battle_1_positive",  -- +4 MD (untitled)
    "wh3_dlc25_nur_battle_2_positive_blessed",  -- +30 Armour (untitled)
    "wh3_dlc25_nur_random_plague_3_force_positive",  -- +20 Armour, +10 Weapon Strength (untitled)
    "wh3_dlc25_nur_battle_2_positive",  -- +15 Armour (untitled)
    "wh3_dlc25_nur_battle_3_positive_blessed",  -- +20% Missile Resistance (untitled)
    "wh3_dlc25_nur_random_plague_2_force_positive",  -- +15% Missile Resistance (untitled)
    "wh3_dlc25_nur_battle_3_positive",  -- +10% Missile Resistance (untitled)
    "wh3_dlc24_ritual_cth_mos_steel_army_combat_buff",  -- Celestial Intervention
    "wh3_nur_plague_component_recipe_5_own_force",  -- Nurgle’s Rot
    "wh3_dlc27_hef_white_tower_ritual_life_army_instant_heal",  -- +20% Physical Resistance (+ one-off heal)
    "wh3_dlc27_nor_monstrous_arcanum_decoy_dilemma_7_option_1",  -- +15% Ward Save, +6 Leadership
    "wh3_main_ritual_tze_gg_3_upgraded",  -- Magic Flare
    "wh3_main_ritual_tze_gg_3",  -- Magic Flare
}

local cm = get_cm and get_cm() or cm
local function log(m) if out then out(m) else print(m) end end

local function get_selected_character()
    local ui = cm:get_campaign_ui_manager()
    local cqi = ui and ui:get_char_selected_cqi()
    if cqi and cqi ~= 0 then return cm:get_character_by_cqi(cqi) end
    return nil
end

local function get_faction_leader()
    local faction = cm:get_local_faction(true) or cm:get_local_faction()
    if not faction or faction:is_null_interface() then return nil end
    local leader = faction:faction_leader()
    if leader and not leader:is_null_interface() then return leader end
    return nil
end

local function run()
    local target = (APPLY_TO == "faction") and get_faction_leader() or get_selected_character()
    if not target or target:is_null_interface() then
        log("apply_bundles: ERROR - no valid target (" .. APPLY_TO .. "). Select a character first.")
        return
    end
    local mf = target:military_force()
    if not mf or mf:is_null_interface() then
        log("apply_bundles: ERROR - target has no army (embedded hero? garrisoned?). Select a lord with a force.")
        return
    end
    local force_cqi = mf:command_queue_index()
    local added = 0
    for _, key in ipairs(BUNDLES) do
        if key and key ~= "" then
            cm:apply_effect_bundle_to_force(key, force_cqi, TURNS)
            added = added + 1
            log("apply_bundles: applied '" .. tostring(key) .. "' to force " .. tostring(force_cqi))
        end
    end
    log("apply_bundles: done - " .. tostring(added) .. " bundle(s) applied for " ..
        (TURNS == 0 and "permanent" or (tostring(TURNS) .. " turns")) .. ".")
end

run()
