--------------------------------------------------------------------------------
-- kairos_skills.lua
-- Auto-generated by make_apply_skills_lua.py.
-- Skills: 48
--
-- Run via the TWW3 "run arbitrary lua" console mod. Force-adds the skills below
-- to the SELECTED character (or the faction leader if APPLY_TO="faction") via
--     cm:force_add_skill(character_lookup_string, skill_key)
-- which bypasses rank / skill-point / own-tree checks. Off-tree skills (grafted
-- from other characters) are flagged in the comments below.
--------------------------------------------------------------------------------

local APPLY_TO = "character"   -- "character" (selected) or "faction" (leader)

-- character_skills ids to add
local SKILLS = {
    "wh3_main_skill_tze_locus_of_transmogrification",  -- Locus of Transmogrification
    "wh3_main_skill_tze_cultist_unique_gate_of_tzeentch",  -- Gate of Tzeentch
    "wh3_main_skill_tze_kairos_magic_core_1",  -- Fate…
    "wh3_main_skill_tze_kairos_magic_core_2",  -- Is…
    "wh3_main_skill_tze_kairos_magic_core_3",  -- Mine…
    "wh3_main_skill_tze_kairos_magic_core_4",  -- To…
    "wh3_main_skill_tze_kairos_magic_core_5",  -- Command!
    "wh3_main_skill_tze_kairos_magic_extra_starter",  -- Greater Arcane Conduit
    "wh3_main_skill_tze_kairos_magic_extra_1",  -- Gaze to the Past
    "wh3_main_skill_tze_kairos_magic_extra_2",  -- Dwell in the Present
    "wh3_main_skill_tze_kairos_magic_extra_4",  -- Gaze to the Future
    "wh3_main_skill_tze_kairos_magic_extra_capstone",  -- Prescient Cant
    "wh3_main_skill_innate_tze_kairos",  -- Oracle
    "wh3_main_skill_tze_kairos_self_oracle_of_eternity",  -- Oracle of Eternity
    "wh3_main_skill_tze_kairos_self_2",  -- The Oracle
    "wh3_main_skill_tze_kairos_self_3",  -- Wind Summoner
    "wh3_main_skill_tze_kairos_self_4",  -- Boons of Change
    "wh3_main_skill_tze_kairos_self_5",  -- Irridescent Scriveners
    "wh3_main_skill_tze_kairos_self_6",  -- Thaumaturgic Rejuvenation
    "wh3_main_skill_tze_kairos_self_8",  -- Bewitching Potency
    "wh3_main_skill_tze_all_unique_missile_resist",  -- Invulnerable Through Change
    "wh2_main_skill_ll_self_defense",  -- Renowned & Feared
    "wh3_main_skill_tze_lord_unique_gaze_of_fate",  -- Gaze of Fate
    "wh3_main_skill_tze_lord_unique_hidden_in_time",  -- Hidden in Time
    "wh3_main_skill_tze_lord_army_buff_1_1",  -- Accursed Horrors
    "wh3_main_skill_tze_lord_army_buff_1_2",  -- Myriad Servants
    "wh3_main_skill_tze_lord_army_buff_1_3",  -- Many-Coloured Fires
    "wh3_main_skill_tze_lord_army_buff_1_4",  -- Riders of Change
    "wh3_main_skill_tze_lord_army_buff_1_5",  -- Warped Retainers
    "wh3_main_skill_tze_lord_army_buff_3_1",  -- Horrific Advancement
    "wh3_main_skill_tze_lord_army_buff_3_2",  -- Arsenal of Insanity
    "wh3_main_skill_tze_lord_army_buff_3_3",  -- Incendiary Ascent
    "wh3_main_skill_tze_lord_army_buff_3_4",  -- Armour of Delirium
    "wh3_main_skill_tze_lord_army_seer_of_destiny",  -- Seer of Destiny
    "wh3_main_skill_tze_lord_army_master_of_fates",  -- Master of Fates
    "wh_main_skill_all_lord_battle_inspiring_presence",  -- Inspiring Presence
    "wh_main_skill_all_lord_campaign_route_marcher",  -- Route Marcher
    "wh_main_skill_all_lord_campaign_lightning_strike",  -- Lightning Strike
    "wh3_main_skill_all_mentor_lord",  -- Mentor
    "wh3_main_skill_tze_generic_hates_nurgle",  -- Hates Nurgle
    "wh3_main_skill_tze_kairos_campaign_public_order",  -- Control Through Confusion
    "wh3_main_skill_tze_kairos_campaign_ambush",  -- Elementals of Surprise
    "wh3_main_skill_tze_kairos_campaign_changing_of_the_ways_cooldown",  -- Binding of the Wills
    "wh3_main_skill_tze_kairos_campaign_changing_of_the_ways_cost",  -- Reckoning of Transmogrification
    "wh3_main_skill_tze_kairos_campaign_intention_insight",  -- All Intents & Purposes
    "wh3_main_skill_tze_lord_campaign_grimoires",  -- Scrolls of Destiny
    "wh3_main_skill_tze_lord_campaign_upkeep",  -- Called by Change
    "wh3_main_skill_tze_lord_campaign_replenish",  -- Legions of Madness
}

local cm = get_cm and get_cm() or cm
local function log(m) if out then out(m) else print(m) end end

local function get_selected_character()
    local ui = cm:get_campaign_ui_manager()
    local cqi = ui and ui:get_char_selected_cqi()
    if cqi and cqi ~= 0 then return cm:get_character_by_cqi(cqi) end
    return nil
end

local function get_faction_leader()
    local faction = cm:get_local_faction(true) or cm:get_local_faction()
    if not faction or faction:is_null_interface() then return nil end
    local leader = faction:faction_leader()
    if leader and not leader:is_null_interface() then return leader end
    return nil
end

local function run()
    local target = (APPLY_TO == "faction") and get_faction_leader() or get_selected_character()
    if not target or target:is_null_interface() then
        log("apply_skills: ERROR - no valid target (" .. APPLY_TO .. "). Select a character first.")
        return
    end
    local lookup = cm:char_lookup_str(target)
    local added = 0
    for _, key in ipairs(SKILLS) do
        if key and key ~= "" then
            cm:force_add_skill(lookup, key)
            added = added + 1
            log("apply_skills: added '" .. tostring(key) .. "'")
        end
    end
    log("apply_skills: done - " .. tostring(added) .. " skill(s) added.")
end

run()
