--------------------------------------------------------------------------------
-- kairos.lua
-- Auto-generated by make_apply_items_lua.py from items.txt.
-- Items: 10   Mode: equipped
--
-- Run via the TWW3 "run arbitrary lua" console mod. Grants the ancillaries below
-- to the SELECTED character (or the faction leader if APPLY_TO="faction").
-- This is the scripted form of the mod's `item <id>` command, batched.
--------------------------------------------------------------------------------

local APPLY_TO     = "character"   -- "character" (selected) or "faction" (leader)
local FORCE_EQUIP  = true       -- true = equip immediately (overwrites same slot)
local ADD_TO_POOL  = false       -- true = drop in faction item pool, don't equip
local SUPPRESS_UI  = true

-- ancillary ids to add
local ITEMS = {
    "wh3_main_anc_armour_scintillating_shield",  -- Scintillating Shield (Armour)
    "wh_main_anc_arcane_item_forbidden_rod",  -- Forbidden Rod (Arcane Item)
    "wh3_dlc24_anc_enchanted_item_book_of_secrets",  -- Book of Secrets (Enchanted Item)
    "wh2_main_anc_talisman_sapphire_guardian_phoenix",  -- Sapphire Guardian Phoenix (Talisman)
    "wh3_main_anc_weapon_staff_of_change",  -- Staff of Change (Weapon)
    "wh3_main_anc_follower_personal_sycophant",  -- Personal Sycophant (General)
    "wh3_main_anc_follower_the_dark_princes_paramour",  -- The Dark Prince’s Paramour (General)
    "wh3_main_anc_follower_tze_sorcerers_apprentice",  -- Sorcerer's Apprentice (General)
    "wh3_main_anc_magic_standard_icon_of_sorcery",  -- Icon of Sorcery (General)
    "wh3_main_anc_follower_tze_tzeentchian_philosopher",  -- Tzeentchian Philosopher (General)
}

local cm = get_cm and get_cm() or cm

local function get_selected_character()
    local ui = cm:get_campaign_ui_manager()
    local cqi = ui and ui:get_char_selected_cqi()
    if cqi and cqi ~= 0 then return cm:get_character_by_cqi(cqi) end
    return nil
end

local function get_faction_leader()
    local faction = cm:get_local_faction(true) or cm:get_local_faction()
    if not faction or faction:is_null_interface() then return nil end
    local leader = faction:faction_leader()
    if leader and not leader:is_null_interface() then return leader end
    return nil
end

local function add_item(character, ancillary_key)
    if ADD_TO_POOL then
        cm:add_ancillary_to_faction(character:faction(), ancillary_key, SUPPRESS_UI)
    else
        cm:force_add_ancillary(character, ancillary_key, FORCE_EQUIP, SUPPRESS_UI)
    end
    out("apply_selected_items: added '" .. tostring(ancillary_key) .. "' (equip=" ..
        tostring(FORCE_EQUIP) .. ", pool=" .. tostring(ADD_TO_POOL) .. ")")
end

local function run()
    local target = (APPLY_TO == "faction") and get_faction_leader() or get_selected_character()
    if not target or target:is_null_interface() then
        out("apply_selected_items: ERROR - no valid target (" .. APPLY_TO .. "). Select a character first.")
        return
    end
    for _, key in ipairs(ITEMS) do
        if key and key ~= "" then add_item(target, key) end
    end
    out("apply_selected_items: done (" .. tostring(#ITEMS) .. " items).")
end

run()
