--------------------------------------------------------------------------------
-- apply_selected_traits.lua
-- Auto-generated by make_apply_lua.py from highlighted rows in traits.xlsx.
-- Colour: #92D050 (green)    Traits: 143
--
-- Run via a TWW3 "run arbitrary lua" console command. Applies the traits below
-- to the currently SELECTED character (or the faction leader if APPLY_TO="faction").
--
-- Combined effects of this set (stacking summed):
--   * Enemy Hero action success chance: -43%
--   * Hero self-defence: +10% chance of wounding aggressors
--   * Leadership aura size: +130% when attacking
--   * Melee attack: +39
--   * Leadership: +4 when attacking
--   * Construction cost: -67% for all buildings
--   * Income from all buildings: +74%
--   * Ammunition: +65%
--   * Missile strength: +44%
--   * Range: +5%
--   * Character's aura leadership effect: +10
--   * Leadership: +15 during ambushes
--   * Speed: +16%
--   * {{tr:public_order_effect}}: +10
--   * Income from Province Capital/Settlement buildings: +10%
--   * Tradable resources produced: +5%
--   * Income from trade tariffs: +15%
--   * Growth: +125
--   * Physical resistance: +35%
--   * Armour: +71
--   * Melee defence: +61
--   * Weapon strength: +36%
--   * Charge bonus: +85
--   * Ward save: +20%
--   * Bonus vs Large: +60
--   * Spell resistance: +45%
--   * Casualty replenishment rate: +10%
--   * Armour-piercing weapon damage: +20
--   * Unit experience gain: +10%
--   * Leadership aura size: +55%
--   * Recruitment cost: -50% for Cavalry units
--   * Missile resistance: +20%
--   * Leadership: +4 during forest battles
--   * Melee attack: +5 during forest battles
--   * Post battle chance of stealing a magic item: +20%
--   * Bonus vs Infantry: +10
--   * Casualty replenishment rate: +20% for this Lord
--   * Ambush success chance: +20%
--   * Ambush defence chance: +30%
--   * Winds of Magic power reserve capacity: +66   (was +41, +25 from Second Generation)
--   * Barrier hit points: +1000   (from Second Generation)
--   * Spell intensity: +40%   (from Second Generation)
--   * Chance of Winds of Magic changing in strength: +50%   (from Second Generation)
--   * {{tr:effect_technology_research_points_description}}: +20
--   * Hit points: +10%
--   * Recruit rank: +2 for all units
--   * Wound recovery time: -4 turns
--   * Melee attack: +3 for Melee Infantry units
--   * Melee defence: +3 for Melee Infantry units
--   * Campaign movement range: +65%
--   * Attrition: -5% casualties suffered from all attrition
--   * Leadership: +32
--   * Income from post-battle loot: +5%
--   * Reinforcement range: +20%
--   * Diplomatic relations: +10 with Beastmen
--   * Diplomatic relations: +10 with Grand Cathay
--   * Diplomatic relations: +10 with Warriors of Chaos
--   * Diplomatic relations: +10 with Chaos Dwarfs
--   * Diplomatic relations: +10 with Daemons of Chaos
--   * Diplomatic relations: +10 with Dark Elves
--   * Diplomatic relations: +10 with Dwarfs
--   * Diplomatic relations: +10 with Greenskins
--   * Diplomatic relations: +10 with High Elves
--   * Diplomatic relations: +10 with Bretonnia
--   * Diplomatic relations: +10 with Empire
--   * Diplomatic relations: +10 with Khornate factions
--   * Diplomatic relations: +10 with all Kislev factions
--   * Diplomatic relations: +10 with Lizardmen
--   * Diplomatic relations: +10 with Nurglish factions
--   * Diplomatic relations: +10 with Ogre Kingdoms
--   * Diplomatic relations: +10 with Skaven
--   * Diplomatic relations: +10 with Slaaneshi factions
--   * Diplomatic relations: +10 with Tomb Kings
--   * Diplomatic relations: +10 with Tzeentchian factions
--   * Diplomatic relations: +10 with Vampire Coast
--   * Diplomatic relations: +10 with Vampire Counts
--   * Diplomatic relations: +10 with Wood Elves
--   * Income from sacking settlements: +42%
--   * Campaign line of sight: +10%
--   * Enemy leadership: -22
--   * Recruitment cost: -15% for Infantry units
--   * Construction time: -35% for all buildings
--   * Attrition: -15% when under siege
--   * Chance of a plague spreading: -20%
--   * Character experience gain: +7%
--   * Miscast base chance: -110%   (was -10%, -100% from Second Generation)
--   * Magic item drop chance from battle: +10%
--   * Upkeep: -44%
--   * Cooldown: -10% to all spells
--   * Weapon strength: +14% for Infantry units
--   * Charge bonus: +20% for Cavalry units
--   * Upkeep: -10% for Cavalry units
--   * Cooldown: -20% to spells
--   * Melee attack: +10%
--   * Income from raiding: +30%
--   * Recruitment cost: -22%
--   * Name of Power: "Barbstorm"
--   * Name of Power: "Wrathbringer"
--   * Name of Power: "Moonshadow"
--   * Name of Power: "Granitestance"
--   * Passive ability: "Hold the Line!"
--   * Ability: "Stand or Die!"
--   * Name of Power: "Barbedlash"
--   * Name of Power: "Pathguard"
--   * Immune to attrition
--   * Name of Power: "the Dire Overseer"
--   * Name of Power: "Blackstone"
--   * Name of Power: "Wyrmscale"
--   * Name of Power: "Poisonblade"
--   * Enables poison attacks  (x2)
--   * Name of Power: "Headreaper"
--   * Enables magical attacks
--   * Attacks cause "Discouraged" effect, reducing leadership
--   * Name of Power: "Griefbringer"
--   * Name of Power: "the Hand of Wrath"
--   * Ability: "Blood Lust"
--   * Name of Power: "Fatedshield"
--   * Name of Power: "Drakecleaver"
--   * Passive ability: "Regeneration"  (x2)
--   * Name of Power: "Hydrablood"
--   * Enables flaming attacks when fighting against Wood Elves
--   * Attribute: Perfect Vigour
--   * Attribute: Causes Fear
--   * Attribute: Expert Charge Defence
--   * Attribute: Unbreakable  (x2)
--------------------------------------------------------------------------------

local APPLY_TO    = "character"   -- "character" (selected) or "faction" (leader)
local SHOW_MESSAGE = true

-- { trait_id, points }  (points = the console "at <trait> <points>" value)
local TRAITS = {
    { "wh2_main_trait_agent_target_fail", 3 },  -- Golden
    { "wh2_main_trait_attacking_victory", 3 },  -- Assault Expert
    { "wh2_main_trait_builder", 3 },  -- Master Mason
    { "wh2_main_trait_def_assassins_end", 1 },  -- Assassin's End
    { "wh2_main_trait_def_name_of_power_ar_04_barbstorm", 1 },  -- Name of Power: "Barbstorm"
    { "wh2_main_trait_def_name_of_power_ar_07_wrathbringer", 1 },  -- Name of Power: "Wrathbringer"
    { "wh2_main_trait_def_name_of_power_ar_08_moonshadow", 1 },  -- Name of Power: "Moonshadow"
    { "wh2_main_trait_def_name_of_power_ar_09_granitestance", 1 },  -- Name of Power: "Granitestance"
    { "wh2_main_trait_def_name_of_power_ca_07_barbedlash", 1 },  -- Name of Power: "Barbedlash"
    { "wh2_main_trait_def_name_of_power_ca_08_pathguard", 1 },  -- Name of Power: "Pathguard"
    { "wh2_main_trait_def_name_of_power_ca_10_the_dire_overseer", 1 },  -- Name of Power: "the Dire Overseer"
    { "wh2_main_trait_def_name_of_power_co_01_blackstone", 1 },  -- Name of Power: "Blackstone"
    { "wh2_main_trait_def_name_of_power_co_02_wyrmscale", 1 },  -- Name of Power: "Wyrmscale"
    { "wh2_main_trait_def_name_of_power_co_03_poisonblade", 1 },  -- Name of Power: "Poisonblade"
    { "wh2_main_trait_def_name_of_power_co_04_headreaper", 1 },  -- Name of Power: "Headreaper"
    { "wh2_main_trait_def_name_of_power_co_08_griefbringer", 1 },  -- Name of Power: "Griefbringer"
    { "wh2_main_trait_def_name_of_power_co_09_the_hand_of_wrath", 1 },  -- Name of Power: "the Hand of Wrath"
    { "wh2_main_trait_def_name_of_power_co_10_fatedshield", 1 },  -- Name of Power: "Fatedshield"
    { "wh2_main_trait_def_name_of_power_co_11_drakecleaver", 1 },  -- Name of Power: "Drakecleaver"
    { "wh2_main_trait_def_name_of_power_co_12_hydrablood", 1 },  -- Name of Power: "Hydrablood"
    { "wh2_main_trait_defeated_azhag_the_slaughterer", 1 },  -- Greenskinner
    { "wh2_main_trait_defeated_balthasar_gelt", 1 },  -- Metalstorm
    { "wh2_main_trait_defeated_durthu", 1 },  -- Tree Surgeon
    { "wh2_main_trait_defeated_fay_enchantress", 1 },  -- Witchfinder General
    { "wh2_main_trait_defeated_grimgor_ironhide", 1 },  -- Hidestriker
    { "wh2_main_trait_defeated_heinrich_kemmler", 1 },  -- Lichekiller
    { "wh2_main_trait_defeated_helmen_ghorst", 1 },  -- Ghorst or Ghost?
    { "wh2_main_trait_defeated_isabella_von_carstein", 1 },  -- Cruelty Restrained
    { "wh2_main_trait_defeated_karl_franz", 1 },  -- Reikshammer
    { "wh2_main_trait_defeated_kholek_suneater", 1 },  -- Stormblight
    { "wh2_main_trait_defeated_kroq_gar", 1 },  -- Saurussmiter
    { "wh2_main_trait_defeated_lord_mazdamundi", 1 },  -- Spawnkiller
    { "wh2_main_trait_defeated_louen_leoncouer", 1 },  -- Kingslayer
    { "wh2_main_trait_defeated_morghur_the_shadowgave", 1 },  -- Skullslasher
    { "wh2_main_trait_defeated_orion", 1 },  -- Wildhunter
    { "wh2_main_trait_defeated_prince_sigvald", 1 },  -- Pride Assassin
    { "wh2_main_trait_defeated_queen_headtaker", 1 },  -- Verminflail
    { "wh2_main_trait_defeated_sisters_of_twilight", 1 },  -- Twilight Extinguished
    { "wh2_main_trait_defeated_skarsnik", 1 },  -- Sneakysmiter
    { "wh2_main_trait_defeated_teclis", 1 },  -- Ruin Unrestrained
    { "wh2_main_trait_defeated_thorgrim_grudgebearer", 1 },  -- Grudgekiller
    { "wh2_main_trait_defeated_throt", 1 },  -- Deep Cleaner
    { "wh2_main_trait_defeated_tyrion", 1 },  -- Ulthuan Undefended
    { "wh2_main_trait_defeated_ungrim_ironfist", 1 },  -- Slayer King Slayer
    { "wh2_main_trait_defeated_vlad_von_carstein", 1 },  -- Undeath Descendant
    { "wh2_main_trait_defeated_volkmar_the_grim", 1 },  -- Grimsbane
    { "wh2_main_trait_defeated_wurzzag", 1 },  -- Great Green Killer
    { "wh2_main_trait_far_from_capital", 1 },  -- Seasoned Campaigner
    { "wh2_main_trait_fighter", 3 },  -- Dauntless
    { "wh2_main_trait_post_battle_ransom", 1 },  -- Kidnapper
    { "wh2_main_trait_reinforcing", 1 },  -- Liberator
    { "wh2_main_trait_reinforcing_beastmen", 1 },  -- Likes Beastmen
    { "wh2_main_trait_reinforcing_cathay", 1 },  -- Likes Cathay
    { "wh2_main_trait_reinforcing_chaos", 1 },  -- Likes Chaos
    { "wh2_main_trait_reinforcing_chaos_dwarfs", 1 },  -- Likes Chaos Dwarfs
    { "wh2_main_trait_reinforcing_daemons", 1 },  -- Likes Daemons
    { "wh2_main_trait_reinforcing_dark_elves", 1 },  -- Likes Dark Elves
    { "wh2_main_trait_reinforcing_dwarfs", 1 },  -- Likes Dwarfs
    { "wh2_main_trait_reinforcing_greenskins", 1 },  -- Likes Greenskins
    { "wh2_main_trait_reinforcing_high_elves", 1 },  -- Likes High Elves
    { "wh2_main_trait_reinforcing_humans", 1 },  -- Likes Men
    { "wh2_main_trait_reinforcing_khorne", 1 },  -- Likes Khorne
    { "wh2_main_trait_reinforcing_kislev", 1 },  -- Likes Kislev
    { "wh2_main_trait_reinforcing_lizardmen", 1 },  -- Likes Lizardmen
    { "wh2_main_trait_reinforcing_nurgle", 1 },  -- Likes Nurgle
    { "wh2_main_trait_reinforcing_ogre_kingdoms", 1 },  -- Likes Ogre Kingdoms
    { "wh2_main_trait_reinforcing_skaven", 1 },  -- Likes Skaven
    { "wh2_main_trait_reinforcing_slaanesh", 1 },  -- Likes Slaanesh
    { "wh2_main_trait_reinforcing_tomb_kings", 1 },  -- Likes Tomb Kings
    { "wh2_main_trait_reinforcing_tzeentch", 1 },  -- Likes Tzeentch
    { "wh2_main_trait_reinforcing_vampire_coast", 1 },  -- Likes Vampire Coast
    { "wh2_main_trait_reinforcing_vampires", 1 },  -- Likes Vampires
    { "wh2_main_trait_reinforcing_wood_elves", 1 },  -- Likes Wood Elves
    { "wh2_main_trait_sacking", 3 },  -- Spoilator
    { "wh2_main_trait_sea_legs", 1 },  -- Seafarer
    { "wh2_main_trait_stance_astromancy", 1 },  -- Uranologist
    { "wh2_main_trait_stance_channeling", 1 },  -- Devout
    { "wh2_main_trait_stance_forced_march", 1 },  -- Supervisor
    { "wh2_main_trait_stance_stalking", 1 },  -- Hunter
    { "wh2_main_trait_wounded", 1 },  -- Neurotic
    { "wh3_main_prologue_egotist", 1 },  -- Egotist
    { "wh3_main_prologue_honest", 1 },  -- Honest
    { "wh3_main_prologue_saviour", 3 },  -- Saviour
    { "wh3_main_prologue_trait_post_battle_execute", 1 },  -- Headsman
    { "wh3_main_prologue_vengeful", 3 },  -- Vengeful
    { "wh3_main_prologue_warlord", 1 },  -- Warlord
    { "wh3_main_trait_ataman_a_boon_for_all", 1 },  -- A Boon for All
    { "wh3_main_trait_ataman_drillmaster", 1 },  -- Drillmaster
    { "wh3_main_trait_ataman_favours_cavalry", 1 },  -- Favours Cavalry
    { "wh3_main_trait_ataman_favours_infantry", 1 },  -- Favours Infantry
    { "wh3_main_trait_ataman_fiscally_prudent", 1 },  -- Fiscally Prudent
    { "wh3_main_trait_ataman_good_host", 1 },  -- Good Host
    { "wh3_main_trait_ataman_investor", 1 },  -- Investor
    { "wh3_main_trait_ataman_master_builder", 1 },  -- Master Builder
    { "wh3_main_trait_ataman_observant", 1 },  -- Observant
    { "wh3_main_trait_ataman_pioneer", 1 },  -- Pioneer
    { "wh3_main_trait_ataman_pragmatic_defender", 1 },  -- Pragmatic Defender
    { "wh3_main_trait_defeated_greasus_goldtooth", 1 },  -- Cashing Out
    { "wh3_main_trait_defeated_kugath", 1 },  -- Air Freshener
    { "wh3_main_trait_defeated_miao_ying", 1 },  -- Very Cold, Still Aloof
    { "wh3_main_trait_defeated_nkari", 1 },  -- Tyrion Owes Me
    { "wh3_main_trait_defeated_skarbrand", 1 },  -- Bloodquencher
    { "wh3_main_trait_defeated_skrag_the_slaughterer", 1 },  -- Maw’s the Pity
    { "wh3_main_trait_defeated_zhao_ming", 1 },  -- Merciless to Ming
    { "wh3_main_trait_dilemma_dae_ruinous_infusion", 1 },  -- Ruinous Infusion
    { "wh3_main_trait_dilemma_dae_the_princes_mark", 1 },  -- The Prince's Mark
    { "wh3_main_trait_dilemma_kho_brutalised_visage", 1 },  -- Brutalised Visage
    { "wh3_main_trait_dilemma_kho_ironhide", 1 },  -- Ironhide
    { "wh3_main_trait_dilemma_ogr_stomach_reduction_surgery", 1 },  -- Stomach Reduction Surgery
    { "wh3_main_trait_dilemma_ogr_tapestry_of_wounds", 1 },  -- Tapestry of Wounds
    { "wh3_main_trait_dilemma_sla_avatar_of_agony", 1 },  -- Avatar of Agony
    { "wh3_main_trait_dilemma_sla_intoxicating_presence", 1 },  -- Intoxicating Presence
    { "wh3_main_trait_hef_unique_mellindirei", 1 },  -- Stormy
    { "wh3_main_trait_ice_court_battler", 1 },  -- Battler
    { "wh3_main_trait_ice_court_blessed_are_the_footsoldiers", 1 },  -- Blessed are the Footsoldiers
    { "wh3_main_trait_ice_court_blessed_cavalry", 1 },  -- Blessed Cavalry
    { "wh3_main_trait_ice_court_builder", 1 },  -- Builder
    { "wh3_main_trait_ice_court_campaigner", 1 },  -- Campaigner
    { "wh3_main_trait_ice_court_cavalry_focused", 1 },  -- Cavalry-Focused
    { "wh3_main_trait_ice_court_cavalry_focused_hero", 1 },  -- Cavalry-Focused
    { "wh3_main_trait_ice_court_economist", 1 },  -- Economist
    { "wh3_main_trait_ice_court_fighter", 1 },  -- Fighter
    { "wh3_main_trait_ice_court_growth_is_great", 1 },  -- Growth is Great
    { "wh3_main_trait_ice_court_infantry_focused_hero", 1 },  -- Infantry-Focused
    { "wh3_main_trait_ice_court_magical_warrior", 1 },  -- Magical Warrior
    { "wh3_main_trait_ice_court_magical_warrior_hero", 1 },  -- Magical Warrior
    { "wh3_main_trait_ice_court_martial_encouragement", 1 },  -- Martial Encouragement
    { "wh3_main_trait_ice_court_martial_encouragement_hero", 1 },  -- Martial Encouragement
    { "wh3_main_trait_ice_court_martial_magician", 1 },  -- Martial Magician
    { "wh3_main_trait_ice_court_raider", 1 },  -- Raider
    { "wh3_main_trait_ice_court_ranger", 1 },  -- Ranger
    { "wh3_main_trait_ice_court_ranger_hero", 1 },  -- Ranger
    { "wh3_main_trait_ice_court_sacker", 1 },  -- Sacker
    { "wh3_main_trait_ice_training_architect", 1 },  -- Architect
    { "wh3_main_trait_ice_training_architect_hero", 1 },  -- {{tr:character_trait_levels_onscreen_name_wh3_main_trait_ice_training_architect}}
    { "wh3_main_trait_ice_training_economist", 1 },  -- {{tr:character_trait_levels_onscreen_name_wh3_main_trait_ice_court_economist}}
    { "wh3_main_trait_ice_training_economist_hero", 1 },  -- {{tr:character_trait_levels_onscreen_name_wh3_main_trait_ice_court_economist}}
    { "wh3_main_trait_ice_training_logistician", 1 },  -- Logistician
    { "wh3_main_trait_ice_training_logistician_hero", 1 },  -- {{tr:character_trait_levels_onscreen_name_wh3_main_trait_ice_training_logistician}}
    { "wh3_main_trait_ice_training_quartermaster", 1 },  -- Quartermaster
    { "wh3_main_trait_ice_training_quartermaster_hero", 1 },  -- {{tr:character_trait_levels_onscreen_name_wh3_main_trait_ice_training_quartermaster}}
    { "wh3_main_trait_ice_training_unbreakable", 1 },  -- {{tr:character_trait_levels_onscreen_name_wh3_main_trait_ice_court_unbreakable}}
    { "wh3_main_trait_ice_training_unbreakable_hero", 1 },  -- {{tr:character_trait_levels_onscreen_name_wh3_main_trait_ice_court_unbreakable}}
    -- Second Generation (Mazdamundi's unique Slann trait): Barrier hit points +1000,
    -- Spell intensity +40%, Winds of Magic change chance +50%, WoM reserve cap +25, Miscast base chance -100%
    { "wh3_main_trait_slann_second_generation_mazdamundi", 1 },  -- Second Generation
}

local cm = get_cm and get_cm() or cm

local function get_selected_character()
    local ui = cm:get_campaign_ui_manager()
    local cqi = ui and ui:get_char_selected_cqi()
    if cqi and cqi ~= 0 then return cm:get_character_by_cqi(cqi) end
    return nil
end

local function get_faction_leader()
    local faction = cm:get_local_faction(true) or cm:get_local_faction()
    if not faction or faction:is_null_interface() then return nil end
    local leader = faction:faction_leader()
    if leader and not leader:is_null_interface() then return leader end
    return nil
end

local function apply_trait(character, trait_id, points)
    local lookup = cm:char_lookup_str(character)
    if points and points > 0 then
        cm:force_add_trait(lookup, trait_id, SHOW_MESSAGE, points)
    else
        cm:force_add_trait(lookup, trait_id, SHOW_MESSAGE)
    end
    out("apply_selected_traits: added '" .. tostring(trait_id) ..
        "' (points " .. tostring(points or 0) .. ") to cqi " ..
        tostring(character:command_queue_index()))
end

local function run()
    local target = (APPLY_TO == "faction") and get_faction_leader() or get_selected_character()
    if not target or target:is_null_interface() then
        out("apply_selected_traits: ERROR - no valid target (" .. APPLY_TO .. "). Select a character first.")
        return
    end
    for _, entry in ipairs(TRAITS) do
        if entry[1] and entry[1] ~= "" then apply_trait(target, entry[1], entry[2] or 0) end
    end
    out("apply_selected_traits: done (" .. tostring(#TRAITS) .. " traits).")
end

run()
