--------------------------------------------------------------------------------
-- kairos_early.lua
-- Auto-generated by make_units.py from kairos.csv (army "early").
-- Units: 19 in 5 entries.
--
-- Run via the TWW3 "run arbitrary lua" console mod. Adds the units below to the
-- SELECTED character's army (or the faction leader's if APPLY_TO="faction").
-- This is the scripted, batched form of the mod's `au <unit> <amount>` command.
--------------------------------------------------------------------------------

local APPLY_TO    = "character"   -- "character" (selected) or "faction" (leader)
local SUPPRESS_UI = true

-- { { unit_key, count }, ... }
local UNITS = {
    { "wh3_main_tze_inf_pink_horrors_0", 7 },  -- Pink Horrors of Tzeentch
    { "wh3_main_tze_mon_flamers_0", 4 },  -- Flamers of Tzeentch
    { "wh3_main_tze_inf_forsaken_0", 4 },  -- Forsaken of Tzeentch
    { "wh3_main_tze_mon_screamers_0", 2 },  -- Screamers of Tzeentch
    { "wh3_main_tze_inf_chaos_furies_0", 2 },  -- Chaos Furies (Tzeentch)
}

local cm = get_cm and get_cm() or cm
local function log(m) if out then out(m) else print(m) end end

local function get_selected_character()
    local ui = cm:get_campaign_ui_manager()
    local cqi = ui and ui:get_char_selected_cqi()
    if cqi and cqi ~= 0 then return cm:get_character_by_cqi(cqi) end
    return nil
end

local function get_faction_leader()
    local faction = cm:get_local_faction(true) or cm:get_local_faction()
    if not faction or faction:is_null_interface() then return nil end
    local leader = faction:faction_leader()
    if leader and not leader:is_null_interface() then return leader end
    return nil
end

local function run()
    local target = (APPLY_TO == "faction") and get_faction_leader() or get_selected_character()
    if not target or target:is_null_interface() then
        log("make_units: ERROR - no valid target (" .. APPLY_TO .. "). Select a character first.")
        return
    end
    local lookup = cm:char_lookup_str(target)
    local added = 0
    for _, row in ipairs(UNITS) do
        local key, count = row[1], row[2]
        if key and key ~= "" and count and count > 0 then
            for _ = 1, count do
                cm:grant_unit_to_character(lookup, key)
                added = added + 1
            end
            log("make_units: added " .. tostring(count) .. "x '" .. tostring(key) .. "'")
        end
    end
    log("make_units: done - " .. tostring(added) .. " unit(s) added to this army.")
end

run()
