#!/usr/bin/env python3
"""
make_apply_skills_lua.py  -  Turn a list of skill ids into an apply-skills Lua
                             script for the TWW3 "run arbitrary lua" console mod.

This is the SKILLS twin of make_apply_items_lua.py / make_apply_lua.py. Where
traits use cm:force_add_trait and items use cm:force_add_ancillary, skills use

    cm:force_add_skill(character_lookup_string, skill_key)

which unlocks the skill on the SELECTED character regardless of rank, skill
points, or whether the skill is even in that character's own skill tree. That
last part is the useful bit: it lets you graft OFF-TREE skills onto a lord -
e.g. give Kairos "Locus of Transmogrification" or "Gate of Tzeentch", abilities
his own tree never offers - because those abilities ride on a skill container
(see all_effects.xlsx: an `..._ability_enable_...` effect is granted by a skill,
item, or trait; it is never applied on its own).

Workflow
--------
1. Put one skill id per line in <kit>/<kit>_skills.txt (blank lines and #comments
   ignored; inline "id   # note" is fine). Skill ids are character_skills keys,
   e.g. wh3_main_skill_tze_kairos_self_4.

2. Generate the Lua, naming the kit so the output is easy to apply:
       python3 make_apply_skills_lua.py kairos
   -> reads kairos/kairos_skills.txt, writes kairos/kairos_skills.lua, and prints
      each skill's onscreen name pulled from WH3-Dump so you see what you granted.
   (With no name it falls back to skills.txt -> apply_selected_skills.lua.)

Options
  --txt PATH      id list to read              (default: <kit>/<kit>_skills.txt)
  --dump PATH     WH3-Dump dir for skill names (default: ./WH3-Dump)
  --out PATH      Lua file to write            (default: <kit>/<kit>_skills.lua)
  --apply-to      character | faction          (default: character)
"""
from __future__ import annotations
import argparse
import os

HERE = os.path.dirname(os.path.abspath(__file__))


# --------------------------------------------------------------------------
def read_ids(path: str):
    """Return list of (id, inline_note) from the txt file, order preserved."""
    ids = []
    with open(path, encoding="utf-8") as f:
        for raw in f:
            line = raw.rstrip("\n")
            if not line.strip() or line.lstrip().startswith("#"):
                continue
            note = ""
            if "#" in line:
                line, note = line.split("#", 1)
                note = note.strip()
            key = line.strip()
            if key:
                ids.append((key, note))
    return ids


def load_skill_names(dump_dir: str):
    """character_skills key -> onscreen name, from WH3-Dump loc. {} if absent."""
    loc = os.path.join(dump_dir, "text", "db", "character_skills__.loc.tsv")
    if not os.path.exists(loc):
        return {}
    names = {}
    prefix = "character_skills_localised_name_"
    with open(loc, encoding="utf-8") as f:
        for line in f:
            parts = line.rstrip("\n").split("\t")
            if len(parts) < 2 or not parts[0].startswith(prefix):
                continue
            key = parts[0][len(prefix):]
            name = parts[1].strip()
            if key and name:
                names[key] = name
    return names


# --------------------------------------------------------------------------
LUA_TEMPLATE = '''--------------------------------------------------------------------------------
-- {out_name}
-- Auto-generated by make_apply_skills_lua.py.
-- Skills: {n}
--
-- Run via the TWW3 "run arbitrary lua" console mod. Force-adds the skills below
-- to the SELECTED character (or the faction leader if APPLY_TO="faction") via
--     cm:force_add_skill(character_lookup_string, skill_key)
-- which bypasses rank / skill-point / own-tree checks. Off-tree skills (grafted
-- from other characters) are flagged in the comments below.
--------------------------------------------------------------------------------

local APPLY_TO = "{apply_to}"   -- "character" (selected) or "faction" (leader)

-- character_skills ids to add
local SKILLS = {{
{skill_lines}
}}

local cm = get_cm and get_cm() or cm
local function log(m) if out then out(m) else print(m) end end

local function get_selected_character()
    local ui = cm:get_campaign_ui_manager()
    local cqi = ui and ui:get_char_selected_cqi()
    if cqi and cqi ~= 0 then return cm:get_character_by_cqi(cqi) end
    return nil
end

local function get_faction_leader()
    local faction = cm:get_local_faction(true) or cm:get_local_faction()
    if not faction or faction:is_null_interface() then return nil end
    local leader = faction:faction_leader()
    if leader and not leader:is_null_interface() then return leader end
    return nil
end

local function run()
    local target = (APPLY_TO == "faction") and get_faction_leader() or get_selected_character()
    if not target or target:is_null_interface() then
        log("apply_skills: ERROR - no valid target (" .. APPLY_TO .. "). Select a character first.")
        return
    end
    local lookup = cm:char_lookup_str(target)
    local added = 0
    for _, key in ipairs(SKILLS) do
        if key and key ~= "" then
            cm:force_add_skill(lookup, key)
            added = added + 1
            log("apply_skills: added '" .. tostring(key) .. "'")
        end
    end
    log("apply_skills: done - " .. tostring(added) .. " skill(s) added.")
end

run()
'''


def build_lua(ids, names, out_name, apply_to):
    lines = []
    for key, note in ids:
        label = names.get(key) or note
        comment = f"  -- {label}" if label else ""
        lines.append(f'    "{key}",{comment}')
    return LUA_TEMPLATE.format(
        out_name=out_name, n=len(ids), apply_to=apply_to,
        skill_lines="\n".join(lines),
    )


def main():
    ap = argparse.ArgumentParser(
        description="ids in <kit>_skills.txt -> <kit>_skills.lua apply-skills Lua.")
    ap.add_argument("name", nargs="?",
                    help="Kit name: reads <name>/<name>_skills.txt, writes <name>_skills.lua (e.g. kairos).")
    ap.add_argument("--txt", help="Explicit id list to read (overrides the default).")
    ap.add_argument("--dump", default=os.path.join(HERE, "WH3-Dump"),
                    help="WH3-Dump dir for skill-name annotations.")
    ap.add_argument("--out", help="Explicit Lua file to write (overrides the default).")
    ap.add_argument("--apply-to", choices=["character", "faction"], default="character")
    args = ap.parse_args()

    # A named kit lives in its own subdir: <HERE>/<kit>/<kit>_skills.txt -> <kit>_skills.lua.
    base = args.name or "skills"
    if base == "skills":
        txt_path = args.txt or os.path.join(HERE, "skills.txt")
        out_path = args.out or os.path.join(HERE, "apply_selected_skills.lua")
    else:
        kit_dir = os.path.join(HERE, base)
        os.makedirs(kit_dir, exist_ok=True)
        default_txt = os.path.join(kit_dir, f"{base}_skills.txt")
        # backward-compat: fall back to a root-level <kit>_skills.txt
        if not args.txt and not os.path.exists(default_txt):
            legacy = os.path.join(HERE, f"{base}_skills.txt")
            if os.path.exists(legacy):
                default_txt = legacy
        txt_path = args.txt or default_txt
        out_path = args.out or os.path.join(kit_dir, f"{base}_skills.lua")

    if not os.path.exists(txt_path):
        raise SystemExit(f"No id list at {txt_path}. Create it (one skill id per line).")

    ids = read_ids(txt_path)
    if not ids:
        raise SystemExit(f"No ids found in {txt_path}. Add one skill id per line.")
    names = load_skill_names(args.dump)

    lua = build_lua(ids, names, os.path.basename(out_path), args.apply_to)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(lua)

    # ---- printed summary ----
    print(f"Read {len(ids)} skill id(s) from {os.path.relpath(txt_path, HERE)}:\n")
    unknown = []
    for key, note in ids:
        name = names.get(key)
        if not name:
            unknown.append(key)
            print(f"  - {key}   (name not in dump{': ' + note if note else ''})")
        else:
            print(f"  - {name}   [{key}]{'  ' + note if note else ''}")
    if unknown:
        print(f"\n  ! {len(unknown)} id(s) had no name in the dump (typo? still written to Lua).")

    print(f"\nWrote Lua -> {out_path}")


if __name__ == "__main__":
    main()
