#!/usr/bin/env python3
"""
make_apply_items_lua.py  -  Turn a tiny list of ancillary (item) ids into an
                            apply-items Lua script for the TWW3 "run lua" mod.

Workflow
--------
1. Put one ancillary id per line in a <kit>.txt file (blank lines and #comments
   ignored; inline "id   # note" is fine). These are the same ids the mod's
   `item <id>` command takes - equipment OR followers OR banners, any mix.

2. Generate the Lua, naming the kit so the output is easy to apply:
       python3 make_apply_items_lua.py kairos
   -> reads kairos.txt and writes kairos.lua, printing a summary (name /
      category / effects) pulled from items.xlsx so you see what each id does.
   (With no name it falls back to items.txt -> apply_selected_items.lua.)

Slots
-----
Equipment (weapon/armour/talisman/arcane item/enchanted item/mount) is ONE slot
each. Followers + banners share the character's 5 ANCILLARY slots - the script
warns if you list more than 5 of those, or two of the same equipment slot.

The generated Lua adds every item to the SELECTED character via the CA API
    cm:force_add_ancillary(character, ancillary_key, force_equip, suppress_event)
which is exactly what the mod's `item <id>` command does under the hood - so it
respects nothing (faction lock, uniqueness, slot rules are all bypassed).

Options
  --txt PATH      id list to read              (default: ./items.txt)
  --xlsx PATH     items sheet for annotations  (default: ./items.xlsx)
  --out PATH      Lua file to write            (default: ./apply_selected_items.lua)
  --apply-to      character | faction          (default: character)
  --pool          add to the faction item POOL (unequipped) instead of force-
                  equipping onto the character - use when you'd rather pick the
                  slot yourself in the item screen.
  --no-equip      grant to the character but do NOT auto-equip (force_equip=false)
"""
from __future__ import annotations
import argparse
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))

# Single-slot equipment categories: two of the same overwrite when force-equipped.
SINGLE_SLOT = {"weapon", "armour", "talisman", "arcane item", "enchanted item",
               "mount"}
# Followers + banners (category "general") share the character's ancillary slots.
ANCILLARY_CATEGORY = "general"
ANCILLARY_SLOTS = 5


# --------------------------------------------------------------------------
def read_ids(path: str):
    """Return list of (id, inline_note) from the txt file, order preserved."""
    ids = []
    with open(path, encoding="utf-8") as f:
        for raw in f:
            line = raw.rstrip("\n")
            if not line.strip() or line.lstrip().startswith("#"):
                continue
            note = ""
            if "#" in line:
                line, note = line.split("#", 1)
                note = note.strip()
            key = line.strip()
            if key:
                ids.append((key, note))
    return ids


def load_items_xlsx(path: str):
    """id -> dict(name, category, subcategory, rarity, faction, effects). {} if missing."""
    if not os.path.exists(path):
        return {}
    from openpyxl import load_workbook
    wb = load_workbook(path, read_only=True)
    ws = wb.active
    data = list(ws.iter_rows(values_only=True))
    hdr = data[0]
    I = {h: i for i, h in enumerate(hdr)}

    def col(*needles):
        for h, i in I.items():
            low = str(h or "").lower()
            if all(n in low for n in needles):
                return i
        return None

    c_id = col("item", "id") or col("id")
    c_nm = col("name")
    c_cat = col("category") if col("category") is not None else None
    c_sub = col("subcategory")
    c_rar = col("rarity")
    c_fac = col("faction")
    c_eff = col("effect")
    out = {}
    for r in data[1:]:
        k = r[c_id]
        if not k:
            continue

        def g(ci):
            if ci is None:
                return ""
            v = r[ci]
            return "" if v is None else str(v)
        out[str(k)] = {
            "name": g(c_nm), "category": g(c_cat), "subcategory": g(c_sub),
            "rarity": g(c_rar), "faction": g(c_fac), "effects": g(c_eff),
        }
    return out


# --------------------------------------------------------------------------
LUA_TEMPLATE = '''--------------------------------------------------------------------------------
-- {out_name}
-- Auto-generated by make_apply_items_lua.py from items.txt.
-- Items: {n}   Mode: {mode}
--
-- Run via the TWW3 "run arbitrary lua" console mod. Grants the ancillaries below
-- to the SELECTED character (or the faction leader if APPLY_TO="faction").
-- This is the scripted form of the mod's `item <id>` command, batched.
--------------------------------------------------------------------------------

local APPLY_TO     = "{apply_to}"   -- "character" (selected) or "faction" (leader)
local FORCE_EQUIP  = {force_equip}       -- true = equip immediately (overwrites same slot)
local ADD_TO_POOL  = {add_to_pool}       -- true = drop in faction item pool, don't equip
local SUPPRESS_UI  = true

-- ancillary ids to add
local ITEMS = {{
{item_lines}
}}

local cm = get_cm and get_cm() or cm

local function get_selected_character()
    local ui = cm:get_campaign_ui_manager()
    local cqi = ui and ui:get_char_selected_cqi()
    if cqi and cqi ~= 0 then return cm:get_character_by_cqi(cqi) end
    return nil
end

local function get_faction_leader()
    local faction = cm:get_local_faction(true) or cm:get_local_faction()
    if not faction or faction:is_null_interface() then return nil end
    local leader = faction:faction_leader()
    if leader and not leader:is_null_interface() then return leader end
    return nil
end

local function add_item(character, ancillary_key)
    if ADD_TO_POOL then
        cm:add_ancillary_to_faction(character:faction(), ancillary_key, SUPPRESS_UI)
    else
        cm:force_add_ancillary(character, ancillary_key, FORCE_EQUIP, SUPPRESS_UI)
    end
    out("apply_selected_items: added '" .. tostring(ancillary_key) .. "' (equip=" ..
        tostring(FORCE_EQUIP) .. ", pool=" .. tostring(ADD_TO_POOL) .. ")")
end

local function run()
    local target = (APPLY_TO == "faction") and get_faction_leader() or get_selected_character()
    if not target or target:is_null_interface() then
        out("apply_selected_items: ERROR - no valid target (" .. APPLY_TO .. "). Select a character first.")
        return
    end
    for _, key in ipairs(ITEMS) do
        if key and key ~= "" then add_item(target, key) end
    end
    out("apply_selected_items: done (" .. tostring(#ITEMS) .. " items).")
end

run()
'''


def build_lua(ids, meta, out_name, apply_to, force_equip, add_to_pool):
    lines = []
    for key, note in ids:
        info = meta.get(key)
        label = ""
        if info and info["name"]:
            cat = info["category"]
            label = f'  -- {info["name"]}' + (f' ({cat})' if cat else "")
        elif note:
            label = f"  -- {note}"
        lines.append(f'    "{key}",{label}')
    mode = ("faction pool" if add_to_pool else
            ("equipped" if force_equip else "granted (not equipped)"))
    return LUA_TEMPLATE.format(
        out_name=out_name, n=len(ids), mode=mode, apply_to=apply_to,
        force_equip=str(force_equip).lower(), add_to_pool=str(add_to_pool).lower(),
        item_lines="\n".join(lines),
    )


def main():
    ap = argparse.ArgumentParser(description="ids in <kit>.txt -> <kit>.lua apply-items Lua.")
    ap.add_argument("name", nargs="?", help="Kit name: reads <name>.txt, writes <name>.lua (e.g. kairos).")
    ap.add_argument("--txt", help="Explicit id list to read (overrides <name>.txt).")
    ap.add_argument("--xlsx", default=os.path.join(HERE, "items.xlsx"))
    ap.add_argument("--out", help="Explicit Lua file to write (overrides <name>.lua).")
    ap.add_argument("--apply-to", choices=["character", "faction"], default="character")
    ap.add_argument("--pool", action="store_true", help="Add to faction pool instead of equipping.")
    ap.add_argument("--no-equip", action="store_true", help="Grant but do not auto-equip.")
    args = ap.parse_args()

    # Resolve input/output from the kit name (positional) unless overridden.
    base = args.name or "items"
    default_out = "apply_selected_items.lua" if base == "items" else f"{base}.lua"
    txt_path = args.txt or os.path.join(HERE, f"{base}.txt")
    out_path = args.out or os.path.join(HERE, default_out)

    if not os.path.exists(txt_path):
        raise SystemExit(f"No id list at {txt_path}. Create it (one ancillary id per line).")

    ids = read_ids(txt_path)
    if not ids:
        raise SystemExit(f"No ids found in {txt_path}. Add one ancillary id per line.")
    meta = load_items_xlsx(args.xlsx)

    force_equip = not args.no_equip
    lua = build_lua(ids, meta, os.path.basename(out_path),
                    args.apply_to, force_equip, args.pool)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(lua)

    # ---- printed summary + slot-conflict warnings ----
    print(f"Read {len(ids)} item id(s) from {os.path.basename(txt_path)}:\n")
    by_cat = {}          # category -> [names]  (for slot accounting)
    unknown = []
    for key, note in ids:
        info = meta.get(key)
        if not info:
            unknown.append(key)
            print(f"  - {key}   (not in items.xlsx{': ' + note if note else ''})")
            continue
        cat = (info["category"] or "").lower()
        by_cat.setdefault(cat, []).append(info["name"] or key)
        eff = info["effects"].replace("\n", " | ")
        eff = (eff[:90] + "…") if len(eff) > 90 else eff
        print(f"  - {info['name']}  [{cat or '?'}{'/' + info['subcategory'] if info['subcategory'] else ''}]"
              f"{'  ' + eff if eff else ''}")

    # single-slot equipment: >1 of the same category overwrites
    eq_warns = [f"{c}: {', '.join(n)}" for c, n in by_cat.items()
                if c in SINGLE_SLOT and len(n) > 1]
    if eq_warns:
        print("\n  ! equipment slot conflict (only the LAST equips if FORCE_EQUIP):")
        for w in eq_warns:
            print(f"      {w}")

    # followers + banners share the 5 ancillary slots
    anc = by_cat.get(ANCILLARY_CATEGORY, [])
    if anc:
        state = "OK" if len(anc) <= ANCILLARY_SLOTS else "OVER"
        print(f"\n  ancillary slots (followers + banners): {len(anc)}/{ANCILLARY_SLOTS}  [{state}]")
        if len(anc) > ANCILLARY_SLOTS:
            print(f"      ! {len(anc) - ANCILLARY_SLOTS} too many - the extras won't fit; trim the list.")

    if unknown:
        print(f"\n  ! {len(unknown)} id(s) not found in items.xlsx (typo? still written to Lua).")

    print(f"\nWrote Lua -> {out_path}")
    print("Mode: " + ("faction pool" if args.pool else
                       ("equipped" if force_equip else "granted, not equipped")))


if __name__ == "__main__":
    main()
