#!/usr/bin/env python3
"""
make_units.py  -  Turn a CSV army list into per-army "add units" Lua scripts for
                  the TWW3 "run arbitrary lua" console mod.

Workflow
--------
1. Write a CSV (header required) with columns:
       unit_id, num_units, army_name[, note]
   - unit_id    : a main_units key, i.e. the same key the mod's `au <unit> <amt>`
                  command takes (e.g. wh3_main_tze_mon_exalted_flamers_0).
   - num_units  : how many copies of that unit to add (integer).
   - army_name  : groups rows into one army -> one Lua file. Rows with the same
                  army_name are batched together.
   - note       : optional free-text comment (ignored if a real unit name is
                  found in the WH3-Dump loc).

2. Generate the Lua, one file per army:
       python3 make_units.py kairos.csv
   The CSV stem ("kairos") is the GENERAL name. Each distinct army_name yields
       kairos_<army_name>.lua
   e.g. army_name "late" -> kairos_late.lua.

   General/faction is just the file stem, so `make_units.py cathay.csv` writes
   cathay_<army>.lua, etc.

Options
  --dump PATH      WH3-Dump dir for unit-name annotations (default: ./WH3-Dump)
  --apply-to       character | faction   (default: character)
  --out-dir PATH   where to write the .lua files (default: alongside the CSV)
  --army NAME      only build this one army_name (default: all)

The generated Lua adds each unit to the SELECTED character's army (or the faction
leader's, with --apply-to faction) via the CA campaign API
    cm:grant_unit_to_character(cm:char_lookup_str(character), unit_key)
called `num_units` times per row - the scripted, batched form of `au`. The target
must be a general with an army; an army holds 19 non-lord units, so the script
warns if an army_name totals more than that.
"""
from __future__ import annotations
import argparse
import csv
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ARMY_UNIT_CAP = 19   # non-lord slots in a campaign army


# --------------------------------------------------------------------------
def read_csv(path: str):
    """Return (rows, order) where rows[army] = [(unit_id, count, note), ...]
    and `order` preserves first-seen army_name order."""
    rows: dict[str, list[tuple[str, int, str]]] = {}
    order: list[str] = []
    with open(path, encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        # normalise header names (strip/lower) so "Num Units" etc. still work
        field_map = {(h or "").strip().lower(): h for h in (reader.fieldnames or [])}

        def col(*names):
            for n in names:
                if n in field_map:
                    return field_map[n]
            return None

        c_id = col("unit_id", "unit", "id", "key")
        c_n = col("num_units", "num", "count", "amount", "qty")
        c_army = col("army_name", "army", "name")
        c_note = col("note", "comment", "label")
        if not (c_id and c_n and c_army):
            raise SystemExit(
                f"CSV must have columns unit_id, num_units, army_name (found: "
                f"{reader.fieldnames}).")

        for i, r in enumerate(reader, start=2):
            uid = (r.get(c_id) or "").strip()
            army = (r.get(c_army) or "").strip()
            raw_n = (r.get(c_n) or "").strip()
            note = (r.get(c_note) or "").strip() if c_note else ""
            if not uid or not army:
                continue  # skip blank/partial lines
            try:
                n = int(float(raw_n))
            except ValueError:
                raise SystemExit(f"Row {i}: num_units '{raw_n}' is not a number.")
            if n <= 0:
                continue
            if army not in rows:
                rows[army] = []
                order.append(army)
            rows[army].append((uid, n, note))
    return rows, order


def load_unit_names(dump_dir: str):
    """main_units key -> onscreen unit name, from WH3-Dump land_units loc. {} if absent."""
    loc = os.path.join(dump_dir, "text", "db", "land_units__.loc.tsv")
    if not os.path.exists(loc):
        return {}
    names = {}
    prefix = "land_units_onscreen_name_"
    with open(loc, encoding="utf-8") as f:
        for line in f:
            parts = line.rstrip("\n").split("\t")
            if len(parts) < 2 or not parts[0].startswith(prefix):
                continue
            key = parts[0][len(prefix):]
            name = parts[1].strip()
            if key and name:
                names[key] = name
    return names


# --------------------------------------------------------------------------
LUA_TEMPLATE = '''--------------------------------------------------------------------------------
-- {out_name}
-- Auto-generated by make_units.py from {csv_name} (army "{army}").
-- Units: {total} in {rows} entr{y_plural}.
--
-- Run via the TWW3 "run arbitrary lua" console mod. Adds the units below to the
-- SELECTED character's army (or the faction leader's if APPLY_TO="faction").
-- This is the scripted, batched form of the mod's `au <unit> <amount>` command.
--------------------------------------------------------------------------------

local APPLY_TO    = "{apply_to}"   -- "character" (selected) or "faction" (leader)
local SUPPRESS_UI = true

-- {{ {{ unit_key, count }}, ... }}
local UNITS = {{
{unit_lines}
}}

local cm = get_cm and get_cm() or cm
local function log(m) if out then out(m) else print(m) end end

local function get_selected_character()
    local ui = cm:get_campaign_ui_manager()
    local cqi = ui and ui:get_char_selected_cqi()
    if cqi and cqi ~= 0 then return cm:get_character_by_cqi(cqi) end
    return nil
end

local function get_faction_leader()
    local faction = cm:get_local_faction(true) or cm:get_local_faction()
    if not faction or faction:is_null_interface() then return nil end
    local leader = faction:faction_leader()
    if leader and not leader:is_null_interface() then return leader end
    return nil
end

local function run()
    local target = (APPLY_TO == "faction") and get_faction_leader() or get_selected_character()
    if not target or target:is_null_interface() then
        log("make_units: ERROR - no valid target (" .. APPLY_TO .. "). Select a character first.")
        return
    end
    local lookup = cm:char_lookup_str(target)
    local added = 0
    for _, row in ipairs(UNITS) do
        local key, count = row[1], row[2]
        if key and key ~= "" and count and count > 0 then
            for _ = 1, count do
                cm:grant_unit_to_character(lookup, key)
                added = added + 1
            end
            log("make_units: added " .. tostring(count) .. "x '" .. tostring(key) .. "'")
        end
    end
    log("make_units: done - " .. tostring(added) .. " unit(s) added to this army.")
end

run()
'''


def build_lua(units, names, out_name, csv_name, army, apply_to):
    lines = []
    for key, count, note in units:
        label = names.get(key) or note
        comment = f"  -- {label}" if label else ""
        lines.append(f'    {{ "{key}", {count} }},{comment}')
    total = sum(c for _, c, _ in units)
    return LUA_TEMPLATE.format(
        out_name=out_name, csv_name=csv_name, army=army, total=total,
        rows=len(units), y_plural=("y" if len(units) == 1 else "ies"),
        apply_to=apply_to, unit_lines="\n".join(lines),
    )


def main():
    ap = argparse.ArgumentParser(
        description="CSV (unit_id,num_units,army_name) -> per-army add-units Lua.")
    ap.add_argument("csv", help="Army CSV. Stem is the general name (kairos.csv -> kairos_<army>.lua).")
    ap.add_argument("--dump", default=os.path.join(HERE, "WH3-Dump"),
                    help="WH3-Dump dir for unit-name annotations.")
    ap.add_argument("--apply-to", choices=["character", "faction"], default="character")
    ap.add_argument("--out-dir", help="Where to write .lua files (default: next to the CSV).")
    ap.add_argument("--army", help="Only build this one army_name.")
    args = ap.parse_args()

    # Resolve the CSV, trying (in order): the path as given, the kit subdir
    # (<HERE>/<stem>/<stem>.csv, e.g. kairos/kairos.csv), then the script dir.
    csv_path = args.csv if os.path.isabs(args.csv) else os.path.join(os.getcwd(), args.csv)
    base = os.path.basename(args.csv)
    stem = re.sub(r"\.csv$", "", base, flags=re.I)
    for cand in (csv_path,
                 os.path.join(HERE, stem, base),   # kit subdir: kairos/kairos.csv
                 os.path.join(HERE, base)):         # script dir
        if os.path.exists(cand):
            csv_path = cand
            break
    if not os.path.exists(csv_path):
        raise SystemExit(f"No CSV at {args.csv}. Columns: unit_id, num_units, army_name.")

    general = re.sub(r"\.csv$", "", os.path.basename(csv_path), flags=re.I)
    out_dir = args.out_dir or os.path.dirname(csv_path) or "."
    os.makedirs(out_dir, exist_ok=True)

    rows, order = read_csv(csv_path)
    if not rows:
        raise SystemExit(f"No usable rows in {os.path.basename(csv_path)}.")
    names = load_unit_names(args.dump)

    wanted = [a for a in order if (not args.army or a == args.army)]
    if args.army and not wanted:
        raise SystemExit(f"army_name '{args.army}' not found. Available: {', '.join(order)}")

    print(f"General: {general}   Armies: {', '.join(order)}\n")
    for army in wanted:
        units = rows[army]
        safe = re.sub(r"[^0-9A-Za-z._-]+", "_", army).strip("_") or "army"
        out_name = f"{general}_{safe}.lua"
        out_path = os.path.join(out_dir, out_name)
        lua = build_lua(units, names, out_name, os.path.basename(csv_path), army, args.apply_to)
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(lua)

        total = sum(c for _, c, _ in units)
        state = "OK" if total <= ARMY_UNIT_CAP else "OVER"
        print(f"[{army}] {total}/{ARMY_UNIT_CAP} units [{state}] -> {out_name}")
        for key, count, note in units:
            label = names.get(key) or note or "(name not in dump)"
            print(f"    {count:>2}x {key}   {label}")
        if total > ARMY_UNIT_CAP:
            print(f"    ! {total - ARMY_UNIT_CAP} over the 19-unit army cap (plus the lord). "
                  f"The extras won't fit - trim the list.")
        print()


if __name__ == "__main__":
    main()
